In [3]:
import numpy as np
#Addition
var=np.array([1,2,3,4])
var_add=var+1
print(var_add)

[2 3 4 5]


In [4]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
x=var1+var2
print(x)

[2 4 6 8]


In [5]:
#subtration

var1=np.array([11,22,33,44])
var2=np.array([1,2,3,4])
x=var1-var2
print(x)

[10 20 30 40]


In [8]:
# divide >>-- reminder

var3=np.array([11,27,31,44])
new_var=var3%3
print(new_var)

[2 0 1 2]


### 2D

In [10]:
v1=[[1,2,3],[2,3,4]]
v2=[[4,1,4],[9,5,6]]
v3=np.add(v1,v2)
print(v3)

[[ 5  3  7]
 [11  8 10]]


### Functions

In [12]:
var=np.array([2,3,5,6,7,8,9])
print("min",np.min(var),np.argmin(var))
print("max",np.max(var),np.argmax(var))
print("cumsum",np.cumsum(var))

min 2 0
max 9 6
cumsum [ 2  5 10 16 23 31 40]
