In [2]:
import numpy as np
var1=np.array([1,2,3])
var2=np.array([3,4,5,6])
x=var1+var2
print(x)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [5]:
var2=np.array([1,2,3])
print(var1.shape)
print()
print(var1)
var2=np.array([[1],[2],[4]])
print(var2.shape)
print()
print(var2)

(3,)

[1 2 3]
(3, 1)

[[1]
 [2]
 [4]]


In [6]:
print(var1+var2)

[[2 3 4]
 [3 4 5]
 [5 6 7]]
