In [2]:
# Rand
# generate number btween 0 to 1

import numpy as np
var=np.random.rand(4)
print(var)

[0.52445303 0.59736103 0.02274747 0.91182388]


In [3]:
import numpy as np
var1=np.random.rand(2,5)
print(var1)

[[0.75013755 0.74593413 0.10282577 0.89589431 0.40765473]
 [0.17933072 0.97736489 0.1792011  0.40584515 0.16387823]]


In [4]:
# randn
# generate random value close to zero
# may return +ve and -ve value

var2=np.random.rand(2,5)
print(var2)


[[0.04056847 0.31371588 0.86844984 0.17156602 0.95849174]
 [0.34075726 0.4386559  0.23876703 0.14388539 0.06912651]]


In [5]:
# ranf
# for random sampling [0.0,1)

var3=np.random.ranf(5)
print(var3)

[0.05624168 0.50295121 0.99830004 0.63098616 0.43149681]


In [7]:
# randint
#(min,max,total_num)
# can create a range and genereate number between them

var5=np.random.randint(2,10,5)
print(var5)

[8 5 9 7 3]
