### Indexing

In [3]:
# indexing
import numpy as np
var =np.array([9,8,7,3])
print(var)
print(var[0])

[9 8 7 3]
9


In [6]:
#2D
var1=np.array([[12,13,14],[10,22,98]])
print(var1[1,1])

22


In [9]:
#3D
var2=np.array([[[1,2],[3,5]]])
print(var2)

[[[1 2]
  [3 5]]]


In [10]:
print(var2[0,1,1])

5


In [11]:
print(var2[0,0,1])

2


### Slicing

In [14]:

#1D
# x =np.array([9,8,7,3,4,1,6])
print("printing from 8 to 4",x[1:5])

printing from 8 to 4 [8 7 3 4]


In [15]:
#2D
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#a[0:1]
a[:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a[:2,1:3]

array([[2, 3],
       [5, 6]])

In [20]:
np.random.seed(111)
b=np.random.randint(1,500,30).reshape(6,5)
b

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [21]:
b[2:4, 1:4]

array([[456, 442,   8],
       [450, 369, 217]])

In [22]:
print(b[2:4, 1:4])

[[456 442   8]
 [450 369 217]]
