In [1]:
import numpy as np
var2=np.array([2,4,5,7,8,0])
for i in var2:
    print(i)

2
4
5
7
8
0


In [6]:
var2=np.array([[2,4,5],[7,8,0]])

print(var2)
print()

for m in var2:
    print(m)
print()
for j in var2:
    for k in j:
        print(k)

[[2 4 5]
 [7 8 0]]

[2 4 5]
[7 8 0]

2
4
5
7
8
0
