In [4]:
import numpy as np
var=np.array([[2,4,5],[3,8,9]])

print(var)
print()
print(var.shape)

[[2 4 5]
 [3 8 9]]

(2, 3)


In [9]:
var1=np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)

print()
print(var1.shape)


[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


### Reshape

In [11]:
var2=np.array([2,4,5,7,8,0])
x=var2.reshape(3,2)
print(x)

[[2 4]
 [5 7]
 [8 0]]
