In [1]:
import numpy as np

In [3]:
# Zeros
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# Ones

ar_one=np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [5]:
# Range
ar_arn=np.arange(4)
print(ar_arn)


[0 1 2 3]


In [7]:
# diagnoal withh 1
dig=np.eye(3,5)
print(dig)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [13]:
# Linespace
ar_lin=np.linspace(0,20,num=4)
print(ar_lin)

[ 0.          6.66666667 13.33333333 20.        ]
